defaults:
  - machine: local
  - solver: jacobi
  - mlflow: local
  - override hydra/launcher: basic
  - override hydra/callbacks: mlflow_log
  - _self_

# ============================================================
# Global Configuration
# ============================================================

# Experiment Identity
prefix: DEBUG
name: default
experiment_name: ${prefix}-${name}

# Problem Size
N: 64

# Parallelization
n_ranks: 4

# Hydra Logging
job_name: null
log_dir: logs/lsf

hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
